// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnuofecykdoukjjnqbgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudW9mZWN5a2RvdWtqam5xYmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5OTQ2OTIsImV4cCI6MjA5OTU3MDY5Mn0.Jkwrkxk2xRhvc-xPbTbTNNoLdXstTGHcfEx1jxfBRRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});